### PR TITLE
Add 'expand_user_macros' option

### PR DESCRIPTION
**Pull request by awiddersheim**
With the addition of the new action menu capabilities to Thruk there is
an added need to allow $USERx$ macros to be expanded while still
limiting their exposure when a host/service command line or custom
variable is expanded.

The 'expand_user_macros' option allows for granular control over which
$USERx$ macros are expanded when the command line and custom variables
are expanded while still allowing server actions the ability to use any
$USERx$ macro.

This new option also still retains the ability of completely turn off
the expansion of all $USERx$ macros by just not specifying anything in
the configuration. To turn expansion on for all macros simply
specifiying 'ALL' will do the trick.

The comparison between the $USERx$ macros and the values supplied in
'expand_user_macros' is not currently capable of handling regular
expressions. This seemed a bit overkill but if there is a good value add
then it can certainly be changed to do so in the future.

Documentation was updated to reflect all of the changes including a few
clarifying changes to the action menu peices that show $USERx$ macros
are now supported and how to specify multiple arguments to server
actions.

### CODE REVIEW

**Comment by awiddersheim** [comment]
I was just thinking about this a bit more. Perhaps it would be better to do a simple ranging system. Something like this for example instead of maybe doing regular expressions or the simple matching that is done now:

```
expand_user_macros = 1
expand_user_macros = 30-40 # $USER30$ - $USER40$
expand_user_macros = 1-256 # all $USERx$ macros more or less
```

**Comment by sni** [comment]
I think a combination would be good. While reading the diff, i realized, that shinken allows all kind of macros in the resource file. So regular expressions and numbers would be good. And i think it should default to 'ALL' since that is the default right now.

**Comment by sni** [comment]
Please also have a look at the t/100-model_Thruk.t test case which does some macro expansion testing and fails atm.

**Comment by awiddersheim** [comment]
So, shinken can have macros that aren't in the form of `$USERx$` in the ```resource.cfg``` file? I"m looking through their documentation and not really finding that.

**Comment by sni** [comment]
I am not aware of any documentation. But yes, you can put whatever matches the form $...$ in there.
Ex.: $PLUGINPATH$ or similar.

**Comment by awiddersheim** [comment]
I think I'll just add the code to support regular expressions. Basically, make things work exactly how ```show_custom_vars``` works. However, I was looking at the code and am a bit confused on some of the code. Specificlaly, the following:

**Comment by awiddersheim** [comment]
Pushed a new commit with some of the suggestions. I ended up not doing the ranges as this isn't something I need at the moment and am running short on time to make that happen. Certainly something that can be added in the feature should someone want to do it though.

Also, added test. The old ones should work since I reverted things so macros get expanded by default. These new tests are to make sure just the ```expand_user_macros``` peice works as expected.

Didn't run the tests myself yet. Figured I'd let travis do the first go for me and if they don't work go from there.

**Comment by awiddersheim** [comment]
@sni This should be good to go now if you could take another look when time permits.

**Comment by awiddersheim** [comment]
Did you want me to rebase this?

**Comment by sni** [comment]
no, that ok. i just had no time to review it yet

**Comment by sni** [comment]
Thanks, i just merged everything and added number expansion, so using USER1-4 works too. Also i changed the default to expand everything, since this is the way it is right now.

**Comment by awiddersheim** [comment]
Nice on the number expansion. I think the 'ALL' stuff is extra IMO. The way I had it after https://github.com/sni/Thruk/commit/226398108dec4819857a158cefe6d430597a2f25 should have been expanding everything by default if nothing was put in for the `expand_user_macros` option.

**Comment by awiddersheim** [comment]
If you want to keep the 'ALL' stuff which is fine. I kind of like it more this way, I'd revert to using some stuff in https://github.com/awiddersheim/Thruk/commit/698fb717782c92f2316c21a48da288aa21c2bf3b. I can send a pull request later today with the changes I think should get made.

**Comment by sni** [comment]
I must admit i never tried an empty list :-) But yes, i'd like to keep it like that so if you want to revert a few things, just send a new request.

**Pull request closed without merging**
