### PR TITLE
Added documentation for OMD multi-site

### PR DESCRIPTION
**Pull request by steaksauce-**
I have created documentation for creating a Thruk multi-site with OMD to address a commonly asked question along the lines of "how do I expose data for one client without exposing data for other clients?".

**NOTE:** This is not meant to be an all inclusive guide for setting up an environment for this task. It is simply meant to be a quick demonstration of one of the ways this question can be answered.

It's also worth noting that this one should be considered a _**draft**_, as I am not fluent in the asciidoc format, and I may have inadvertently mentioned bad practices.

Should this be merged, there should probably be a link in the FAQ and README as well.

### CODE REVIEW

**Comment by steaksauce-** [comment]
@sni any thoughts on this? Do you think it belongs in OMD (in addition to this OR OMD only)?

**Comment by sni** [comment]
I like it, i am just thinking about the best place to put it

**Comment by steaksauce-** [comment]
Thanks for the quick update!

**Comment by sni** [comment]
merged, thank you very much. I also added a link in the faq to your article.

**Pull request merged**
