### PR TITLE
fix #1180

### LINKED ISSUE #1180: Wrong Formating in Panorama-View
If you use a service-grid on all Browsers but Firefox and Internetexplorer the header with the service-names is to small

In FF and IE everything works fine ... also in Chrome until a few weeks ago

### PR DESCRIPTION
**Pull request by themoonisacheese**

### CODE REVIEW

**Comment by sni** [comment]
nice, good catch. Thanks for looking into it. The only thing which worries me is that this change will break all old chrome installations. So i guess we need some kind of version check in the panorama js.

**Comment by themoonisacheese** [comment]
probably the case indeed. i don't have access to an old chrome install to check, and documentation on this is sparse.

**Comment by sni** [comment]
Merged it now assuming chrome rolls out updates pretty fast.

**Comment by themoonisacheese** [comment]
should be good for all internet-connected chrome installs. from what i can gather it is pretty much impossible to not update chrome in that case. thanks for your work 👍

**Pull request merged**
