### PR TITLE
fix insecure dependency error in unlink

### PR DESCRIPTION
**Pull request by santuari**
While restarting Thruk, I got an exception:

`Insecure dependency in unlink while running with -T switch at /var/lib/neteye/thruk/plugins/plugins-enabled/reports2/lib/Thruk/Utils/Reports.pm line 778.`

The solution proposed verifies that the path is safe and that the unlink variable is untainted.

### CODE REVIEW

**Comment by sni** [comment]
can't we just use `Thruk::Utils::IO::untaint($dir);` here?

**Comment by santuari** [comment]
It does not work.
I guess that the problem is somehow the variable + the regex in the unlink(...($dir.'/*.sh'))

**Comment by sni** [comment]
Cannot reproduce it anyway. Which version is that and what exactly is required to reproduce this issue?

**Comment by santuari** [comment]
Version is 2.20-2
I have 20-30 reports configured, and some of them are Schedule. 
If I restart thruk, I got that error and the crontab is not correctly generated: the scheduled reports are missing.

**Comment by sni** [comment]
how do you restart thruk and what linux is that?

**Comment by santuari** [comment]
Centos 6, perl v5.10.1

First start thruk:
`/etc/init.d/thruk start`
and the error is triggered by (not the restart itself):
`/usr/bin/thruk -a installcron --local`

Sorry for the misunderstanding.

**Pull request closed without merging**
