### PR TITLE
Add a method to insert a section at the given index

### PR DESCRIPTION
**Pull request by vaxvms**
It allow to add a section between two existing sections without redefining the
complete menu in thruk_local.conf

### CODE REVIEW

**Comment by sni** [comment]
very nice. Could you please add also add a short description here: https://github.com/sni/Thruk/blob/master/docs/documentation/menu.asciidoc

**Comment by vaxvms** [comment]
Doh, i screw up. Should i submit a new pull request ?

**Comment by sni** [comment]
Don't worry. That happens if you `git pull` which usualy results in an merge. You can still do a `git pull --rebase` followed by a `git push -f` to sort things out.

**Comment by sni** [comment]
looks better now, except there are two insert_sections now :-)

**Comment by vaxvms** [comment]
Seems good this time \o/

**Comment by sni** [comment]
Looks good, merged. Thank you.

**Pull request merged**
