### PR TITLE
Improve IE11 compatibility

### PR DESCRIPTION
**Pull request by ofosos**
We are having problem with Thruk rendering in IE 7 compatibilty mode and thus not working properly on IE. This fixes the problem by forcing Edge rendering mode on "modern" browsers.

### CODE REVIEW

**Comment by sni** [comment]
hmm, we changed that setting back and forth in all directions already, see https://github.com/sni/Thruk/pull/459
I came to the conclusion that there is no right value for the ie compatibility mode, so i would opt for a new configuration option. On the other hand, afaik it is possible already to configure the compat mode in IE itself for specific domains.

**Comment by ofosos** [comment]
Hi sni,
what about changing the doctype declaration to be something more like HTML5?

**Comment by ofosos** [comment]
Basically the problem is that IE falls back to IE7 mode for Thruk, but I'm not sure if this is some strange configuration on our clients or this is due to the doctype declaration.

**Comment by ofosos** [comment]
I think so. Browser compatibility uses some weird heuristics, I'll
check tomorrow.
 
--
Mark Meyer
mark@ofosos.org
 
 
On Mon, Jul 11, 2016, at 07:38 PM, Sven Nierlein wrote:
> Thruk doesn't really use HTML5 features. Would the doctype change the
> compatibility mode?
> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].
>
 

Links:

  1. https://github.com/sni/Thruk/pull/618#issuecomment-231807480
  2. https://github.com/notifications/unsubscribe/AA2R7xNPGt0tcpf58Owg6nGGrsLwGG0zks5qUn9-gaJpZM4JICS2

**Comment by ofosos** [comment]
Yep, a simple HTML5 doctype declaration, i.e.

<!DOCTYPE html>

works around my problems. In fact it works very well. I can't see any drawbacks to this, but it is not strictly in compliance with the spec, when we have stuff like <link ... **/**>. Since this is an XML artefact.

I applied the doctype changes to a branch and tested a little. Should I PR these changes?

**Comment by sni** [comment]
Right now, the doctype is spec compliant, so i don't like the idea to replace that with a non compliant header just to make IEs compatibility mode heuristic work. I'd still would add another config option to set the ie compat mode. This should make everyone happy since everyone can set it to whatever they want.

**Comment by ofosos** [comment]
Hmm, I'll look into it, but I think I was wrong on non-compliance. At least the emtpy tag notation for XHTML <br/> is allowed in HTML. I'm not completely sure, whether XHTML is a proper subset of HTML, but I'll look into it. Functionally this makes no difference. Declaring the document as HTML works at least in my Firefox and my IE 11 browsers. I'll try with some other versions tomorrow and look into whether there's a subset relationship between html and xhtml.

**Comment by ofosos** [comment]
I think there are very specific problems, when switching from XHTML to HTML. E.g. use of CDATA sections, which are allowed in XHTML but not in HTML. I think I will try switching this in our Thruk and run this by a HTML5 validator.

**Pull request closed without merging**
